version: '3.9'

services:
  client:
    image: nginxinc/nginx-unprivileged:mainline-alpine
    restart: on-failure:3
    expose: [ '8080' ]
    ports: [ '${WEB_PORT}:8080' ]
    depends_on: [ 'server', 'blizzard' ]
    environment:
      WEB_HOSTNAME: ${WEB_HOSTNAME}
      GAME_HTTP_HOST: ${GAME_HTTP_HOST}
      GAME_HTTP_PORT: ${GAME_HTTP_PORT}
      GAME_BLIZZARD_HOST: ${GAME_BLIZZARD_HOST}
      GAME_BLIZZARD_PORT: ${GAME_BLIZZARD_PORT}
    volumes:
      - ./.data/dockerize:/usr/local/bin/dockerize:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
      - ./templates/puffle.conf.template:/etc/nginx/conf.d/puffle.conf.template:ro
    command: dockerize -template /etc/nginx/conf.d/puffle.conf.template:/etc/nginx/conf.d/puffle.conf nginx "-g daemon off;"

  server:
    image: node:alpine
    restart: on-failure:3
    user: node
    expose: [ '${GAME_HTTP_PORT}' ]
    networks: [ 'default', 'db' ]
    depends_on: [ 'mariadb' ]
    env_file: [ '.env' ]
    working_dir: /srv/server
    volumes:
      - ./.data/dockerize:/usr/local/bin/dockerize:ro
      - ./server:/srv/server
      - ./templates/config.json.template:/srv/templates/config.json.template:ro
    command: dockerize -template /srv/templates/config.json.template:/srv/server/config/config.json -wait tcp://${MARIADB_HOST}:${MARIADB_PORT} -timeout 20s npm run http

  blizzard:
    image: node:alpine
    restart: on-failure:3
    user: node
    expose: [ '${GAME_BLIZZARD_PORT}' ]
    networks: [ 'default', 'db' ]
    depends_on: [ 'mariadb' ]
    env_file: [ '.env' ]
    working_dir: /srv/server
    volumes:
      - ./.data/dockerize:/usr/local/bin/dockerize:ro
      - ./server:/srv/server
      - ./templates/config.json.template:/srv/templates/config.json.template:ro
    command: dockerize -template /srv/templates/config.json.template:/srv/server/config/config.json -wait tcp://${MARIADB_HOST}:${MARIADB_PORT} -timeout 20s npm run world:blizzard

  mariadb:
    image: mariadb:latest
    restart: on-failure:3
    user: mysql
    expose: [ '3306' ]
    networks: [ 'db' ]
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./.data/mariadb:/var/lib/mysql

  setup:
    profiles: [ 'dev' ]
    image: node:alpine
    networks: [ 'db' ]
    depends_on: [ 'mariadb' ]
    working_dir: /srv/puffle
    env_file: [ '.env' ]
    volumes:
      - ./:/srv/puffle
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache git runuser
        runuser -u node -- sh ./setup.sh

  phpmyadmin:
    profiles: [ 'tools' ]
    image: phpmyadmin
    restart: on-failure:3
    expose: [ '80' ]
    networks: [ 'db' ]
    environment:
      - PMA_HOST=mariadb

networks:
  db:
